name: k_chart
description: A Flutter K Chart.
version: 0.4.0
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.1.0
  built_value: 8.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.0.3
  built_value_generator: 8.0.3

dependency_overrides:
  dart_style: ^2.0.0
  args: ^2.0.0
  analyzer: ^1.7.1

  build_config: 1.0.0


flutter:
